### ISSUE TITLE
Escaped arguments

### ISSUE THREAD

**Issue by arnieggertsson** [mysteriouspants/ArgumentParser#10]
Not seeing how to receive escaped arguments, trying to parse argument containing 
For example a equals symbol.   ( I am receiving a password via command line)

I have tried using backslash to escape the symbol,  I have tried both double and single quotes

**Comment by mysteriouspants** [comment]
Hello, thanks for using Argument Parser!

By "escaped", I assume you're referring to backslash-escaped arguments, such as

    foo -m "This is a \"message\""

This is interpreted by NSProcessInfo (from which Argument Parser reads its arguments) as

    -m
    This is a "message"

There's a lot of string mangling that the shell does before the arguments get to your program, and that mangling also depends on what shell you're using.

Check the documentation of your shell, and inspect the arguments as received by looking at `[[NSProcessInfo currentProcess] arguments]` to see how your arguments actually get received.

If I can be of any more help, do let me know.

**Comment by arnieggertsson** [comment]
Hi,

Thanks for your quick feedback, I had tested all those without luck,
I now think that the problem might be that I cannot escape the equal sign "=" 
I just tried escaping the " sign like in your example and it works fine, it just does something different when I am trying with the equals sign....

**Comment by mysteriouspants** [comment]
Sorry for the delay,

I've just tried, and it doesn't seem that bash requires the equals sign to be escaped. Consider the output of the example program `spiffy`:

    cmiller-mbpwrd:bin cmiller$ ./spiffy -h
    Example program:
          [-i --if]={1,1} Input file
          [-o --of]={1,1} Output file
    cmiller-mbpwrd:bin cmiller$ ./spiffy --if=some=file
      Input File: some=file
      OutputFile: (null)

That's a rather trivial incantation, so it might be broken if you're trying something more complex - if so, let me know so I can get that fixed!

**Comment by mysteriouspants** [comment]
I'm closing this issue for now. Please reopen it should you run into this again!
