### ISSUE TITLE
After pulling up CoreParse this project no longer builds.

### ISSUE THREAD

**Issue by wadeco** [mysteriouspants/ArgumentParser#11]
The issue stems from the way ArgumentParser manually imports files from CoreParse. CoreParse added CPRegexpRecogniser to its umbrella header which cannot be found at build time.

**Comment by mysteriouspants** [comment]
I haven't updated CP because the software works fine as is. Are you using CP elsewhere, and would like to update? If so, I'm more than happy to help upgrade the version of CP That ArgParse uses; if not, I'd suggest that the YAGNI principle applies.

**Comment by wadeco** [comment]
I'm not using CP elsewhere, just doing some clean up and noticed it was lagging. That being said, I think your right, I would most likely not need any of the new changes. So disregard my initial issue, thanks.

**Comment by mysteriouspants** [comment]
I haven't been paying attention to CP in general recently, so I'll keep that in mind next time I take a look at ArgParse.
